version: "2"

services:

    db:
        image: mysql:5.7
        restart: always
        volumes:
            - "dbdata:/var/lib/mysql"
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_general_ci
            - --skip-character-set-client-handshake
        environment:
            MYSQL_ROOT_PASSWORD: pimcore
            MYSQL_DATABASE: pimcore
            MYSQL_USER: pimcore
            MYSQL_PASSWORD: pimcore

    web:
        image: seeruk/docker-nginx:latest
        restart: always
        environment:
            NGINX_TEMPLATE: default-php-pimcore-composer
        volumes:
            - ./:/opt/www
        links:
            - php:php.docker

    php:
        image: seeruk/php-fpm:7.0-dev
        restart: always
        environment:
            TERM: xterm
        volumes:
            - ./:/opt/www
        links:
            - db:db.docker
            - cache:cache.docker

    cache:
        image: memcached
        restart: always

volumes:
    dbdata:
        driver: local